---
nics:
  - name: nic1
    vxlan_name: vxlan0
    type: phy
    network: control_plane
    br_name: brbm
    gateway: true
    mcast_group: 239.0.0.1
    vni: 42
  - name: nic2
    vxlan_name: vxlan1
    type: phy
    network: internal_api
    br_name: br-int-api
    gateway: false
    mcast_group: 239.0.0.2
    vni: 43
  - name: nic3
    vxlan_name: vxlan2
    type: bridge
    br_name: br-mgmt
    mcast_group: 239.0.0.3
    vni: 44
  - name: nic4
    type: vlan
    id: 10
    network: external_api
  - name: nic5
    type: vlan
    id: 20
    network: storage
  - name: nic6
    type: vlan
    id: 30
    network: storage_mgmt
  - name: nic7
    type: vlan
    id: 40
    network: management
