---
- name: "create ovs bridge {{ item['br_name'] }}"
  openvswitch_bridge: bridge="{{ item['br_name'] }}" state=present

- name: "create vxlan interface {{ item['vxlan_name'] }}"
  vxlan: 
    ifname: "{{ item['vxlan_name'] }}" 
    mcast_group: "{{ item['mcast_group'] }}" 
    vxlan_link: "{{ phy_int }}" 
    vni: "{{ item['vni'] }}"
  register: result

- name: "add interface {{ item['vxlan_name'] }} to bridge {{ item['br_name'] }}"
  openvswitch_port: bridge="{{ item['br_name'] }}" port="{{ item['vxlan_name'] }}" state=present
  register: portaddresult

- name: "create virsh net {{ item['br_name'] }} definition"
  template:
    src: virsh-net.xml.j2
    dest: "/tmp/virsh-net_{{ item['br_name'] }}.xml"

- name: "define virsh net {{ item['br_name'] }}"
  virt_net: 
    command: define 
    name: "{{ item['br_name'] }}" 
    xml: '{{ lookup("template", "virsh-net.xml.j2") }}'

- name: "set virsh net {{ item['br_name'] }} autostart"
  virt_net: 
    autostart: yes
    name: "{{ item['br_name'] }}"

- name: "set virsh net {{ item['br_name'] }} active"
  virt_net: 
    state: active
    name: "{{ item['br_name'] }}"
